add_newline = true

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
style = 'bold #4EA1FF'
truncation_length = 5
truncate_to_repo = true
truncation_symbol = "…/"

[cmd_duration]
min_time = 2000
format = 'took [$duration](grey) '

[time]
disabled = false
use_12hr = true
style = 'bold white'
format = '[$time]($style) '

[hostname]
ssh_only = false
style = 'bold white'
format = '[$hostname]($style) [](bold #E95420) '

[git_commit]
tag_disabled = false

[git_branch]
symbol = ' '
style = 'bold #C678DD'
format = 'on [$symbol$branch]($style) '

[git_status]
modified = '!${count} '
staged = '+${count} '
untracked = '?${count} '
deleted = '-${count} '
renamed = '»${count} '
conflicted = '=${count} '
stashed = '$${count} '
ahead = '[↑${count}](bold cyan)'
behind = '↓${count}'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
rebase = 'REBASING'
merge = 'MERGING'

[nodejs]
disabled = true

[package]
symbol = ''
format = 'is [$version](bold yellow) '
