add_newline = true

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
style = 'bold #4EA1FF'
truncation_length = 5
truncate_to_repo = true
truncation_symbol = "…/"

[cmd_duration]
min_time = 2000
format = 'took [$duration](grey) '

[time]
disabled = false
use_12hr = true
style = 'bold white'
format = '[$time]($style) '

[hostname]
ssh_only = false
style = 'bold white'
format = '[$hostname]($style) [](bold #E95420) '

[git_commit]
tag_disabled = false

[git_branch]
symbol = ' '
style = 'bold #C678DD'
format = 'on [$symbol$branch]($style) '

[git_status]
format = '([\[](#777777)$all_status$ahead_behind[\]](#777777))'
modified = '[!${count}](bold #FF9E64) '
staged = '[+${count}](bold #50FA7B) '
untracked = '[?${count}](bold #61AFEF) '
deleted = '[-${count}](bold #FF6E67) '
renamed = '[»${count}](bold #C678DD) '
conflicted = '[=${count}](bold #FF3B3B) '
stashed = '[$${count}](bold #2E8B57) '
ahead = '[↑${count}](bold #00FFFF)'
behind = '[↓${count}](bold #E5C07B)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
rebase = '[REBASING](bold #8D93F9)'
merge = '[MERGING](bold #FFC857)'

[nodejs]
disabled = true

[package]
symbol = ''
format = 'is [$version](bold yellow) '
